### ISSUE TITLE
[MJLINK-1] Dependency Report produces exception based on JDK 9 based JAR file...

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jlink-plugin#507]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** opened **[MJLINK-1](https://issues.apache.org/jira/browse/MJLINK-1?redirect=false)** and commented

currently a site build `mvn -Preporting site site:stage` produces the following error:

```
[INFO] Generating "Dependencies" report  --- maven-project-info-reports-plugin:2.9:dependencies
[WARNING] Unable to process class module-info.class in JarAnalyzer File /Users/kama/.m2/repository/org/ow2/asm/asm/6.0_BETA/asm-6.0_BETA.jar
org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.bcel.classfile.Constant.readConstant(Constant.java:161)
	at org.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:69)
	at org.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:235)
	at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:143)
	at org.apache.maven.shared.jar.classes.JarClassesAnalysis.analyze(JarClassesAnalysis.java:96)
	at org.apache.maven.report.projectinfo.dependencies.Dependencies.getJarDependencyDetails(Dependencies.java:259)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.hasSealed(DependenciesRenderer.java:1542)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails(DependenciesRenderer.java:545)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:240)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:83)
	at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:201)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:229)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:337)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:178)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:132)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Generating "Dependency Convergence" report --- maven-project-info-reports-plugin:2.9:dependency-convergence
```

Need to investigage more in depth. Seemed to be related to maven-project-info-reports-plugin.

---

**Affects:** 3.0.0-alpha-1

**Issue Links:**
- [BCEL-300](https://issues.apache.org/jira/browse/BCEL-300) org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
 (_**"is blocked by"**_)
- [BCEL-301](https://issues.apache.org/jira/browse/BCEL-301) org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 20
 (_**"is blocked by"**_)

**Remote Links:**
- [GitHub Pull Request #245
](https://github.com/apache/maven-jlink-plugin/issues/245)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Based on different updates this works fine now.
