### ISSUE TITLE
[MJLINK-4] NPE on execution 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jlink-plugin#509]
**[Johannes Boesl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=j.boesl)** opened **[MJLINK-4](https://issues.apache.org/jira/browse/MJLINK-4?redirect=false)** and commented

When I try to run my maven build I get the following exception:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jlink-plugin:3.0.0-alpha-1:jlink (default-jlink) on project jloadr-jre: Execution default-jlink of goal org.apache.maven.plugins:maven-jlink-plugin:3.0.0-alpha-1:jlink failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-jlink-plugin:3.0.0-alpha-1:jlink (default-jlink) on project jloadr-jre: Execution default-jlink of goal org.apache.maven.plugins:maven-jlink-plugin:3.0.0-alpha-1:jlink failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-jlink of goal org.apache.maven.plugins:maven-jlink-plugin:3.0.0-alpha-1:jlink failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 11 more
Caused by: java.lang.NullPointerException
	at org.codehaus.plexus.languages.java.jpms.ResolvePathsRequest$1.toPath(ResolvePathsRequest.java:52)
	at org.codehaus.plexus.languages.java.jpms.ResolvePathsRequest$1.toPath(ResolvePathsRequest.java:48)
	at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePaths(LocationManager.java:109)
	at org.apache.maven.plugins.jlink.JLinkMojo.preparePaths(JLinkMojo.java:347)
	at org.apache.maven.plugins.jlink.JLinkMojo.execute(JLinkMojo.java:264)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 12 more
 > 
> ``` 
> 
> The cause seems to be that the following code in line 337 in JLinkMojo returns a collection with only 'null' entries:
> `Collection<File> dependencyArtifacts = getCompileClasspathElements( getProject() );`
```

---

**Affects:** 3.0.0-alpha-1

**Issue Links:**
- [MJLINK-42](https://issues.apache.org/jira/browse/MJLINK-42) NullPointerException when running jlink:jlink
 (_**"is duplicated by"**_)

**Remote Links:**
- [GitHub Pull Request #133
](https://github.com/apache/maven-plugins/pull/133)
- [GitHub Pull Request #248
](https://github.com/apache/maven-jlink-plugin/issues/248)

3 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Can you please make an example project which reproduces the issue...Many thanks...

**Comment by jira-importer** [comment]
**[Johannes Boesl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=j.boesl)** commented

Try to build maven module 'jloadr-jre' at https://github.com/aditosoftware/jloadr/tree/merged

**Comment by jira-importer** [comment]
**[Jochen Mader](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=codepitbull)** commented

I ran into the same issue and created a somewhat smaller example to highlight the problem:

https://github.com/codepitbull/java9playground

**Comment by jira-importer** [comment]
**[Johannes Boesl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=j.boesl)** commented

[Jochen Mader](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=codepitbull) what os did you use? I'm using Ubuntu. Maybe it doesn't occur on windows.

**Comment by jira-importer** [comment]
**[Antonio Petrelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetrelli)** commented

Hello
as you may notice I submitted a pull request for the fix. It works for me. I gathered info from:
https://vzurczak.wordpress.com/2016/01/08/finding-dependencies-artifacts-in-your-maven-plug-in/
The upgrade to Maven 3.1.1 (I was cautious on this) was due to a problem like this:
https://github.com/mrice/license-check/issues/8

**Comment by jira-importer** [comment]
**[Jochen Mader](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=codepitbull)** commented

Updated my deps to 3.0.0-alpha-2-SNAPSHOT and can confirm that the problem is gone.

Thanks everyone for the fix!

**Comment by jira-importer** [comment]
**[Antonio Petrelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetrelli)** commented

It works for me too, thank you!

**Comment by jira-importer** [comment]
**[Bernd Eckenfels](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=b.eckenfels)** commented

Just as an additional note, I had the same issue in alpha.1 and I noticed that using the POM parent `com.soebes.smpp:smpp:2.3.0` would work around it. I guess it updates some shared components or adds something to the model. Anyway.. waiting for alpha.2 :)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Many thanks [Bernd Eckenfels](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=b.eckenfels) for the feedback.
